test: ignore failing tests relating to Selenium (#514)
Fixes errors relating to: 

```
Error:    Axe43xIntegrationTest.worksOnShadowDOMIframes Multiple Failures (2 failures)
	org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Response code 500. Message: session not created: probably user data directory is already in use, please specify a unique value for --user-data-dir argument, or don't use --user-data-dir 
Host info: host: 'fv-az1933-614', ip: '10.1.0.119'
Build info: version: '4.13.0', revision: 'ba948ece5b*'
System info: os.name: 'Linux', os.arch: 'amd64', os.version: '6.11.0-1014-azure', java.version: '17.0.15'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Command: [null, newSession {capabilities=[Capabilities {browserName: chrome, goog:chromeOptions: {args: [--remote-allow-origins=*, --no-sandbox, --log-level=3, --silent, --headless=old, --disable-gpu, --window-size=1920,1200, --ignore-certificate-errors], binary: /opt/google/chrome/google-c..., extensions: []}, unhandledPromptBehavior: accept}]}]
	java.lang.NullPointerException: Cannot invoke "org.openqa.selenium.WebDriver.quit()" because "this.webDriver" is null
```

Ci run:
https://github.com/dequelabs/axe-core-maven-html/actions/runs/15196565945/job/42742046926


No QA Required